### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [nickzahornyi/nickzahornyi.github.io#21]
1 вот этот скрипт у тебя не находит
`<script type="text/javascript" src="js/libs/jquery.xdomainrequest.min.js"></script>`
и этот скрипт должен быть в 
`<script type="text/javascript" src="js/libs.min.js"></script>`
2 на плитке должны быть рамдомные картинки при первой загрузке как [тут](http://speariv35.github.io/GoIT/javascript/exam1/build/), 15 пунтк в тз

**Comment by nickzahornyi** [comment]
Исправил.

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ

**Comment by AndriiLitvin** [comment]
пофиксь вот это http://joxi.ru/n2Y5gPkSjBk6q2

**Comment by nickzahornyi** [comment]
Поправил.
