### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [nickzahornyi/nickzahornyi.github.io#4]
http://joxi.ru/5mdMgP7ixpl421
1) Фокус должен быть такой как ховер
2)Сделать не картинкой а css
3),4)НЕ картинкой а через тег "а" и сss
Форма не отцентрирована по горизонтали и вертикали(при большей ширине экрана это видно) 
менюшка улетает вправо при большей ширине экрана + бекграунд там еще есть картинка

**Comment by nickzahornyi** [comment]
Исправил

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
