### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [nickzahornyi/nickzahornyi.github.io#7]
http://joxi.ru/52aYgPkSGlLng2
добавь max-width
## Экран 960 http://joxi.ru/52aYgPkSGlLY72

1) line-height больше
2)4)  убери вот этот набор font-family: "Open Sans",Tahoma,sans-serif; оставь только Open Sans
3) обрезается текст
5) MORE BLOG POSTS вровень с первым блоком убери вот этот набор font-family: "Open Sans",Tahoma,sans-serif; оставь только Open Sans
6) по всему макету text-shadow и только один из шрифтов либо font-family: LeagueGothic; либо Open Sans
## Экран 768 https://cloud.githubusercontent.com/assets/13675947/12387598/54739702-bdd6-11e5-84d3-21f3eb749616.png  http://joxi.ru/Y2L0zPXsnxyXR2 (в общем как на экране 480) вот этот плагин https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc переделай под него

Экраны
320-479(макет 320)
480-767(макет 480)
768-959( макет 768)
960 (макет 960)

**Comment by nickzahornyi** [comment]
Переделал.

**Comment by AndriiLitvin** [comment]
Зачет. только добавь метатег 

`<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no; target-densityDpi=device-dpi" />`
бо сейчас не подгребает стиля. не видно в консоле браузера

**Comment by nickzahornyi** [comment]
Добавил.
